development:
  adapter: postgresql
  encoding: utf8
  database: word_games_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: word_games_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: word_games_production
  pool: 5

cucumber:
  <<: *TEST